### ISSUE TITLE
android:windowTranslucentStatus是设置为false还是true？设置为false无反应。

### ISSUE THREAD

**Issue by CasparGX** [D-clock/AndroidSystemUiTraining#1]
真机测试，系统4.4.2，设置ColorTranslucentTheme无反应。

``` XML
<item name="android:windowTranslucentStatus">false</item>
<item name="android:windowTranslucentNavigation">true</item>
```

将`android:windowTranslucentStatus`设置为`true`就生效了，这是什么原因？

**Comment by D-clock** [comment]
Android 4.4.x 的平台应该设置 android:windowTranslucentStatus 为 true。5.x才是设置为false，我在工程中的代码也是这样写的啊

**Comment by CasparGX** [comment]
get
是我自己粗心看错了，谢了
