### ISSUE TITLE
华为手机状态栏还是系统的

### ISSUE THREAD

**Issue by chiclaim** [D-clock/AndroidSystemUiTraining#2]
在华为手机下 状态栏还是系统的，系统为Android5.1。EMUI3.1

**Comment by D-clock** [comment]
请问是运行了本工程的代码吗？因为我在 Android 5.1 真机下运行没问题，不知道会不会是EMUI自身的问题，能否提供一下效果截图？

**Comment by stay4cold** [comment]
华为的确实没改过来

**Comment by jelychow** [comment]
华为的是手机的问题,不是代码的问题,建议开发者略过此项,另外我想跟作者交流下toast 位置错位的问题,主要由于Context 不同会引起toast的错位,在初始化toast的时候采用ApplicationContext 不会有错位的问题,toast 是系统级别的ui 建议使用ApplicationContext 来避免在浸入式状态栏显示错误

**Comment by D-clock** [comment]
@jelychow nice，明天尝试一下，之前没有试过用Application Context是否会出现问题。
