### ISSUE TITLE
你的项目有毒，无法导入到androidstudio

### ISSUE THREAD

**Issue by txxxtxx** [D-clock/AndroidSystemUiTraining#3]
感觉你的项目有毒，都无法导入到androidstudio

**Comment by D-clock** [comment]
大哥，你别吓我啊。。。。。。那么多人都导入成功了，你按说明去配置了么?

**Comment by D-clock** [comment]
@txxxtxx 大哥，你别吓我啊。。。。。。那么多人都导入成功了，你按说明去配置了么?

**Comment by txxxtxx** [comment]
直接用的androidstudio上的checkoutfromvcs导入的，导入之后打开不成功，其他的eclipse工程可以这样导入

**Comment by D-clock** [comment]
@txxxtxx 嗯，你试试clone到本地导入试试，导入的配置readme已经说明，你说的方式我没试过哈，回头我整一下！

**Comment by George-Soros** [comment]
我也是导入有问题，一直在加载，gradle的包你项目中没有，readme中的好像没有配置说明吧？
