### ISSUE TITLE
项目结构有问题啊。gralde没法导入，修改了好一会。。。

### ISSUE THREAD

**Issue by xiiaoleii** [D-clock/AndroidSystemUiTraining#4]
项目结构不是用gradle构建的?AS 导入很艰难。。。带来的体验差

**Comment by D-clock** [comment]
@xiiaoleii 嗯，我考虑去改进一下！

**Comment by D-clock** [comment]
@xiiaoleii 刚才没看仔细，我的项目是用gradle构建的啊！导入艰难，是出了什么情况呢？
